# Sample Riprap config file for using filesystem/database plugins.

####################
# General settings #
####################

fixity_algorithm: SHA-1

###########
# Plugins #
###########

plugins.fetchresourcelist: ['PluginFetchResourceListFromGlob']
# Absolute or relative to the Riprap application directory.
resource_dir_paths: ['resources/filesystemexample/resourcefiles']

plugins.fetchdigest: PluginFetchDigestFromShell
digest_command: '/usr/bin/sha1sum'

plugins.persist: PluginPersistToDatabase

plugins.postcheck: ['PluginPostCheckCopyFailures']
# Absolute or relative to the Riprap application directory.
failures_log_path: '/tmp/riprap_failed_events.log'
