# Sample Riprap config file for using Islandora/database plugins.
# Requires that the "Riprap resource list" View be enabled in
# the Islandora instance. This View is bundled with the Islandora Riprap
# module.
#
# This plugin is agnostic to which media have fixity event checks performed
# on them. The filters in the "Riprap resource list" View determine that.
# See the View's filter criteria GUI for examples.

####################
# General settings #
####################

# thin: true
fixity_algorithm: sha256

# Absolute or relative to the Riprap application directory.
failures_log_path: 'var/riprap_failed_events.log'

###################
# Plugin settings #
###################

# Use this plugin if you want to use the 'Riprap resource (media) list' View provided by Islandora Riprap.
plugins.fetchresourcelist: ['PluginFetchResourceListFromDrupalView']
drupal_baseurl: 'http://localhost:8000'
drupal_user: admin
drupal_password: islandora
fedora_baseurl: 'http://127.0.0.1:8080/fcrepo/rest'
# Absolute or relative to the Riprap application directory.
views_pager_data_file_path: 'var/fetchresourcelist.from.drupal.pager.txt'

# Required. Non-standard or custom media need to have the fieldname they use to contain the file added to this list.
drupal_file_fieldnames: ['field_media_audio', 'field_media_document', 'field_edited_text', 'field_media_file', 'field_media_image', 'field_media_video_file']

plugins.fetchdigest: PluginFetchDigestFromFedoraAPI
fedoraapi_method: HEAD
fedoraapi_digest_header_leader_pattern: "^.+="

plugins.persist: PluginPersistToDatabase

plugins.postcheck: ['PluginPostCheckCopyFailures']

