# Sample Riprap config file for using Islandora/database plugins.
# Requires that the "Riprap resource list" View be enabled in
# the Islandora instance. This View is bundled with the Islandora Riprap
# module.

####################
# General settings #
####################

fixity_algorithm: sha256

# Absolute or relative to the Riprap application directory.
failures_log_path: '/tmp/riprap_failed_events.log'

###################
# Plugin settings #
###################

plugins.fetchresourcelist: ['PluginFetchResourceListFromDrupal']
drupal_baseurl: 'http://localhost:8000'
view_authorization_user: admin
view_authorization_password: islandora
use_fedora_urls: true
gemini_endpoint: 'http://localhost:8000/gemini'
gemini_auth_header: 'Bearer islandora' 
# Absolute or relative to the Riprap application directory.
views_pager_data_file_path: 'var/fetchresourcelist.from.drupal.pager.txt'

plugins.fetchdigest: PluginFetchDigestFromFedoraAPI
fedoraapi_method: HEAD
fedoraapi_digest_header_leader_pattern: "^.+="

plugins.persist: PluginPersistToDatabase

plugins.postcheck: ['PluginPostCheckCopyFailures']

