# Sample Riprap config file for using Islandora/database plugins.

####################
# General settings #
####################

fixity_algorithm: sha256

###########
# Plugins #
###########

plugins.fetchresourcelist: ['PluginFetchResourceListFromDrupal']
drupal_baseurl: 'http://localhost:8000'
view_authorization_user: admin
view_authorization_password: islandora
use_fedora_urls: true
gemini_endpoint: 'http://localhost:8000/gemini'
gemini_auth_header: 'Bearer islandora' 
# Absolute or relative to the Riprap application directory.
views_pager_data_file_path: 'var/fetchresourcelist.from.drupal.pager.txt'

plugins.fetchdigest: PluginFetchDigestFromFedoraAPI
fedoraapi_method: HEAD
fedoraapi_digest_header_leader_pattern: "^.+="

plugins.persist: PluginPersistToDatabase

plugins.postcheck: ['PluginPostCheckCopyFailures']
# Absolute or relative to the Riprap application directory.
failures_log_path: '/tmp/riprap_failed_events.log'
