<?php
// src/Plugin/PluginPostCheckMigrateFedora3AuditLog.php

/**
 * This Riprap plugin provides a way to migrate fixity events from a
 * Fedora 3.x repository. It assumes that resources migrated from Fedora 3.x to
 * Fedora 5 include the AUDIT datastream. The plugin is not needed after the
 * fixity events in the AUDIT datastreams for all resources have been persisted
 * to Riprap; when this is achieved the plugin can be disabled.
 *
 *
 */
namespace App\Plugin;

class PluginPostCheckMigrateFedora3AuditLog extends AbstractPostCheckPlugin
{
    public function execute($event)
    {

        # See PluginPostCheckMigrateFedora3AuditLogTest.php for code that implements the following logic.

        # For the current resource, retrieve the binary resource containing its Fedora 3.x AUDIT datastream.
        # Parse out the audit records (XPath $audit_xml->xpath('//audit:record').
        # For each record
            # Get its timestamp (XPath $record->xpath('./audit:date')[0]).
            # Get its justtfication (XPath $record->xpath('./audit:justification')[0]).
            # If the record's justification is 'PREMIS:eventType=fixity check', get the digest algorithm and event
            # outcome from the justification.
            # Persist the record to Riprap's database.

            # Fixity events generated by Islandora's Checksum Checker module do not contain a digest value.
            # We will need to account for that when persisting these events.
    }
}
