You will need to copy one of the following sample configuration files to this location in order to run Riprap:

* services.yaml.filesystemexample
* services.yaml.mockfedorarepository
* services.yaml.islandora

See the Riprap README.md file for more information

